[[main]]
  name = "Inspire"
  url = "/inspire/"
  weight = 10

[[main]]
  name = "Friends of Hack"
  url = "/partners/"
  weight = 20

[[main]]
  identifier = "arsenal"
  name = "Hack Arsenal"
  weight = 30
  url = "/arsenal/"

[[main]]
  name = "Event Agenda"
  weight = 40
  url = "/agenda"

[[main]]
  name = "Get Help"
  weight = 50
  url = "/help/"

[[inspire]]
  name="Industrial Metaverse"
  weight = 10
  url = "/inspire/industry"

[[inspire]]
  name="Metaverse in Retail"
  weight = 20
  url = "/inspire/retail"

[[inspire]]
  name="Metaverse & AI"
  weight = 30
  url = "/inspire/ai"

[[main]]
  identifier = "hardware"
  name = "Hardware"
  weight = 10
  url = "/arsenal/hardware"
  parent = "arsenal"

[[main]]
  identifier = "software"
  name = "Software"
  weight = 20
  url = "/arsenal/software"
  parent = "arsenal"

[[footer]]
  name = "Corporate information"
  url = "https://www.bosch-digital.com/imprint/"

[[footer]]
  name = "Legal notice"
  url = "https://www.bosch-digital.com/legal-notice/"

[[footer]]
  name = "Data protection notice"
  url = "https://www.bosch-digital.com/data-protection-notice/"

[[footer]]
  name = "Privacy Settings"
  url = "https://www.bosch-digital.com/#show-privacy-settings"
